version: '3'

services: 
  capturetheflat: 
    build: 
      context: "."
      dockerfile: CaptureTheFlat/Dockerfile
    image: capturetheflat
    links: 
      - "db:database"
    ports: 
      - "1337:80"
  db:
    ports: 
         - "3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
    image: mariadb